<a href="https://colab.research.google.com/github/FANG87003/2025_ML_hws/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 113-2 深度學習 作業 1

## 一、載入numpy套件

In [1]:
import numpy as np

## 二、定義激活函數 (activation function)

### (1) Sigmoid () 函數

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

### (2) ReLU () 函數

In [3]:
def relu(x):
  return np.maximum(0, x)

### (3) Softmax () 函數

In [4]:
def softmax(x):
  c = np.max(x)
  x -= c
  return np.exp(x) / np.sum(np.exp(x))

## 三、神經網路計算

### 3.1 輸入層

#### (1) 6 個特徵值

In [5]:
import numpy as np

X = np.array([0.5, 0.3, 0.8, 0.2, 0.7, 0.9])  # 6個特徵值
print(X)
print(X.shape) # 一列六行

[0.5 0.3 0.8 0.2 0.7 0.9]
(6,)


### 3.2 第 一 隱藏層

#### (1) 5 個神經元

In [6]:
W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2, 0.1],
    [0.2, 0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6, 0.7],
    [0.7, 0.6, 0.5, 0.4, 0.3]]) # 權重

b1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5]) # 偏值
print(W1.shape) # 六列五行
print(b1.shape)

(6, 5)
(5,)


#### (2) 加權和

In [7]:
z1 = np.dot(X, W1) + b1
print(z1)
print(z1.shape) # 一列五行

[1.42 1.58 1.74 1.9  2.06]
(5,)


#### (3) 激活函數 ReLU ()

In [8]:
h1 = relu(z1)
print(h1)
print(h1.shape) # 一列五行

[1.42 1.58 1.74 1.9  2.06]
(5,)


### 3.3 第 二 隱藏層

#### (1) 4 個神經元

In [9]:
W2 = np.array([
    [0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3],
    [0.4, 0.5, 0.6, 0.7]]) # 權重

b2 = np.array([0.2, 0.3, 0.4, 0.5]) # 偏值
print(W2.shape) # 五列四行
print(b2.shape)

(5, 4)
(4,)


#### (2) 加權和

In [10]:
z2 = np.dot(h1, W2) + b2
print(z2)
print(z2.shape) # 一列四行

[3.76  4.034 4.308 4.582]
(4,)


#### (3) 激活函數 ReLU ()

In [11]:
h2 = relu(z2)
print(h2)
print(h2.shape) # 一列四行

[3.76  4.034 4.308 4.582]
(4,)


### 3.4 第 三 隱藏層

#### (1) 4 個神經元

In [12]:
W3 = np.array([
    [0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3],
    [0.4, 0.5, 0.6, 0.7],
    [0.7, 0.6, 0.5, 0.4]])  # 權重

b3 = np.array([0.3, 0.4, 0.5, 0.6])  # 偏值
print(W3.shape) # 四列四行
print(b3.shape)

(4, 4)
(4,)


#### (2) 加權和

In [13]:
z3 = np.dot(h2, W3) + b3
print(z3)
print(z3.shape) # 一列四行

[8.779  8.8242 8.8694 8.9146]
(4,)


#### (3) 激活函數 sigmoid ()

In [14]:
h3 = sigmoid(z3)
print(h3)
print(h3.shape) # 一列四行

[0.99984609 0.99985289 0.99985939 0.99986561]
(4,)


### 3.5 輸出層

#### (1) 3 個神經元

In [15]:
W4 = np.array([
    [0.5, 0.3, 0.1],
    [0.2, 0.4, 0.6],
    [0.7, 0.5, 0.3],
    [0.6, 0.2, 0.4]])  # 權重

b4 = np.array([0.4, 0.5, 0.6])  # 偏值
print(W4.shape) # 四列三行
print(b4.shape)

(4, 3)
(3,)


#### (2) 加權和

In [16]:
z4 = np.dot(h3, W4) + b4
print(z4)
print(z4.shape) # 一列三行

[2.39971456 1.8997978  1.9998004 ]
(3,)


#### (3) 激活函數 Softmax ()

In [17]:
y_hat = softmax(z4)
print(y_hat)
print(y_hat.shape) # 一列三行

[0.43918231 0.26639971 0.29441798]
(3,)


### 3.6 損失函數 (loss function)

#### (1) 真實結果 y

In [19]:
y = np.array([0, 0, 1])  # x 屬於第 3 種類的機率為 1

#### (2) 交叉熵誤差 (cross_entropy_error)

In [20]:
def cross_entropy_error(y_hat, y):
  return -np.sum(y * np.log(y_hat + 1e-7))

#### (3) y_hat 與 y 之間的誤差值

In [21]:
loss = cross_entropy_error(y_hat, y) #  y_hat 與 y 之間的誤差值
print(f'y_hat 與 y 之間的誤差值: {loss}')

y_hat 與 y 之間的誤差值: 1.2227544845296932


## 四、Gradio套件

### 4.1 安裝 Gradio

In [22]:
!pip install gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 kB 21.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 117.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.5 MB/s eta 0:00:00


### 4.2 載入 Gradio 套件

In [23]:
import gradio as gr

### 4.3 函數dnn ()

In [27]:
def dnn(*x):
  x = np.array(x, dtype=float)

  z1 = np.dot(x, W1) + b1
  h1 = relu(z1)

  z2 = np.dot(h1, W2) + b2
  h2 = relu(z2)

  z3 = np.dot(h2, W3) + b3
  h3 = sigmoid(z3)

  z4 = np.dot(h3, W4) + b4
  y_hat_func = softmax(z4)

  return f'預測類別: {int(np.argmax(y_hat)) + 1}', y_hat_func

### 4.4 建立 Gradio 介面

In [25]:
iface = gr.Interface(dnn,
            inputs=[gr.Number(label=f'特徵值 {i+1}') for i in range(6)],
            outputs=[
                gr.Textbox(label='預測類別'),
                gr.Textbox(label='y_hat 數值')],
            title='DNN 類別預測',
            description='請輸入6個特徵值')
iface.launch(share=True)

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://4e0800b93cf1f36012.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


### 4.5 y_hat 是否相等

In [26]:
_, y_hat_func = dnn(X)
print(y_hat_func) # dnn結果的y_hat
print(y_hat) # 第1項練習的y_hat

if np.allclose(y_hat_func, y_hat):
  print(f'函數dnn()的 y_hat 與第1項練習的 y_hat 相同\n')
else:
  print(f'函數dnn()的 y_hat 與第1項練習的 y_hat 不同\n')

[[0.43918231 0.26639971 0.29441798]]
[0.43918231 0.26639971 0.29441798]
函數dnn()的 y_hat 與第1項練習的 y_hat 相同

