<a href="https://colab.research.google.com/github/3B032132/2025_ML_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 113-2 深度學習 作業 2

In [2]:
import numpy as np

## 一、定義激活函數 (activation function)

### (1) Sigmoid () 函數

In [3]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

### (2) ReLU () 函數

In [4]:
def relu(x):
  return np.maximum(0, x)

### (3) Softmax () 函數

In [5]:
def softmax(x):
  x -= np.max(x, axis=-1, keepdims=True)
  return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

## 二、多層神經網路批次學習

### 2.1 輸入層

#### (1) 批次大小

In [6]:
batch_size = 5

#### (2) 批次輸入 5 筆 X 6 = 30 個特徵值

In [7]:
X = np.array([
    [1.0, 0.5, 0.2, 0.8, 0.3, 0.7],
    [0.9, 0.3, 0.5, 0.4, 0.6, 0.2],
    [0.6, 0.8, 0.7, 0.3, 0.1, 0.9],
    [0.4, 0.6, 0.8, 0.2, 0.5, 0.1],
    [0.3, 0.9, 0.4, 0.7, 0.2, 0.8]]) # 5x6

print('X shape:', X.shape)

X shape: (5, 6)


#### (3) 假設真實結果 Y

In [45]:
Y = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]]) # 5x3

print('Y shape:', Y.shape)

Y shape: (5, 3)


### 2.2 第 一 隱藏層

#### (1) 5 個神經元

In [9]:
W1 = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2, 0.1],
    [0.2, 0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6, 0.7],
    [0.7, 0.6, 0.5, 0.4, 0.3]]) # 6x5

b1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5]) # 1x5

print('W1 shape:', W1.shape)
print('b1 shape:', b1.shape)

W1 shape: (6, 5)
b1 shape: (5,)


#### (2) 加權和 z1

In [15]:
z1 = np.dot(X, W1) + b1

print(z1) # 5x5
print('z1 shape:', z1.shape)

[[1.55 1.6  1.65 1.7  1.75]
 [1.   1.21 1.42 1.63 1.84]
 [1.54 1.58 1.62 1.66 1.7 ]
 [0.94 1.12 1.3  1.48 1.66]
 [1.7  1.65 1.6  1.55 1.5 ]]
z1 shape: (5, 5)


#### (3) 激活函數 ReLU ()

In [16]:
h1 = relu(z1)

print(h1) # 5x5
print('h1 shape:', z1.shape)

[[1.55 1.6  1.65 1.7  1.75]
 [1.   1.21 1.42 1.63 1.84]
 [1.54 1.58 1.62 1.66 1.7 ]
 [0.94 1.12 1.3  1.48 1.66]
 [1.7  1.65 1.6  1.55 1.5 ]]
h1 shape: (5, 5)


### 2.3 第 二 隱藏層

#### (1) 4 個神經元

In [17]:
W2 = np.array([
    [0.2, 0.3, 0.4, 0.5],
    [0.5, 0.4, 0.3, 0.2],
    [0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3],
    [0.4, 0.5, 0.6, 0.7]]) # 5x4

b2 = np.array([0.2, 0.3, 0.4, 0.5]) # 1x4

print(W2.shape)
print(b2.shape)

(5, 4)
(4,)


#### (2) 加權和 z2

In [22]:
z2 = np.dot(h1, W2) + b2

print(z2) # 5x4
print('z2 shape:', z2.shape)

[[3.525 3.79  4.055 4.32 ]
 [3.145 3.387 3.629 3.871]
 [3.46  3.722 3.984 4.246]
 [2.89  3.12  3.35  3.58 ]
 [3.375 3.635 3.895 4.155]]
z2 shape: (5, 4)


#### (3) 激活函數 ReLU ()

In [24]:
h2 = relu(z2)

print(h2) # 5x4
print('h2 shape:', h2.shape)

[[3.525 3.79  4.055 4.32 ]
 [3.145 3.387 3.629 3.871]
 [3.46  3.722 3.984 4.246]
 [2.89  3.12  3.35  3.58 ]
 [3.375 3.635 3.895 4.155]]
h2 shape: (5, 4)


### 2.4 第 三 隱藏層

#### (1) 4 個神經元

In [25]:
W3 = np.array([
    [0.3, 0.4, 0.5, 0.6],
    [0.6, 0.5, 0.4, 0.3],
    [0.4, 0.5, 0.6, 0.7],
    [0.7, 0.6, 0.5, 0.4]]) # 4x4

b3 = np.array([0.3, 0.4, 0.5, 0.6]) #1x4

print(W3.shape)
print(b3.shape)

(4, 4)
(4,)


#### (2) 加權和 z3

In [26]:
z3 = np.dot(h2, W3) + b3

print(z3) # 5x4
print('z3 shape:', z3.shape)

[[8.2775 8.3245 8.3715 8.4185]
 [7.437  7.4886 7.5402 7.5918]
 [8.137  8.1846 8.2322 8.2798]
 [6.885  6.939  6.993  7.047 ]
 [7.96   8.008  8.056  8.104 ]]
z3 shape: (5, 4)


#### (3) 激活函數 sigmoid ()

In [27]:
h3 = sigmoid(z3)

print(h3) # 5x4
print('h3 shape:', h3.shape)

[[0.99974589 0.99975756 0.99976869 0.9997793 ]
 [0.9994113  0.99944089 0.99946899 0.99949568]
 [0.99970757 0.99972116 0.99973412 0.99974648]
 [0.99897803 0.9990317  0.99908255 0.99913074]
 [0.99965097 0.99966732 0.99968291 0.99969776]]
h3 shape: (5, 4)


### 2.5 輸出層

#### (1) 3 個神經元

In [28]:
W4 = np.array([
    [0.5, 0.3, 0.1],
    [0.2, 0.4, 0.6],
    [0.7, 0.5, 0.3],
    [0.6, 0.2, 0.4]]) # 4x3

b4 = np.array([0.4, 0.5, 0.6]) # 1x3

print(W4.shape)
print(b4.shape)

(4, 3)
(3,)


#### (2) 加權和 z4

In [29]:
z4 = np.dot(h3, W4) + b4

print(z4) # 5x3
print('z4 shape:', z4.shape)

[[2.39953012 1.89966699 1.99967145]
 [2.39891953 1.89923338 1.99924463]
 [2.39945979 1.89961709 1.99962228]
 [2.39813159 1.89867351 1.99869389]
 [2.39935564 1.89954323 1.99954947]]
z4 shape: (5, 3)


#### (3) 激活函數 Softmax ()

In [31]:
y_hat = softmax(z4)

print(y_hat) # 5x3
print('y_hat shape:', y_hat.shape)

[[0.43916886 0.26640584 0.2944253 ]
 [0.43912439 0.26642601 0.29444959]
 [0.43916373 0.26640817 0.29442809]
 [0.43906704 0.26645198 0.29448098]
 [0.43915614 0.26641163 0.29443223]]
y_hat shape: (5, 3)


### 2.6 損失函數 (loss function)

#### (1) 交叉熵誤差 (cross_entropy_error)

In [47]:
def cross_entropy_error(y, t):  # (神經網路計算結果, 真實結果)
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)

  batch_size = y.shape[0]
  return -np.sum(t * np.log(y + 1e-7)) / batch_size

#### (2) y_hat 與 Y 之間的誤差值

In [50]:
loss = cross_entropy_error(y_hat, Y)
print(f'y_hat 與 y 之間的誤差值: {loss}')

y_hat 與 y 之間的誤差值: 1.1028129518671288
