<a href="https://colab.research.google.com/github/FANG87003/2025_DL_hws/blob/main/hw6-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 113-2 深度學習 作業 6-2

# 2.請完成課本冒險旅程 26 第 1, 2 題


## 載入套件

In [1]:
import numpy as np

## 輸入

In [2]:
x1 = np.array([0.1, 0.2, 0.3])
x2 = np.array([0.4, 0.1, 0.5])
x3 = np.array([0.6, 0.2, 0.1])

## 權重 & 偏值

In [3]:
Wx = np.array([[0.5, 0.3, 0.2, 0.3],
        [0.9, 0.6, 0.4, 0.8],
        [0.2, 0.8, 0.3, 0.1]])

Wh = np.array([[0.2, 0.4, 0.6, 0.8],
        [0.8, 0.1, 0.7, 0.8],
        [0.3, 0.5, 0.7, 0.6],
        [0.4, 0.5, 0.6, 0.5]])

b = np.array([0.3, 0.6, 0.5, 0.8])

## 起始隱藏狀態為零向量

In [4]:
h0 = np.array([0, 0, 0, 0])

## 定義 RNN 隱藏狀態計算函數

In [5]:
def rnn(x_t, h_t):
  return np.tanh(np.dot(x_t, Wx) + np.dot(h_t, Wh) + b)

## 計算 h1

In [6]:
h1 = rnn(x1, h0)
print(f'h1 = {h1}')

h1 = [0.52989561 0.75736232 0.597982   0.76986654]


## 計算 h2

In [7]:
h2 = rnn(x2, h1)
print(f'h2 = {h2}')

h2 = [0.95530415 0.97331155 0.98657697 0.99296904]


## 計算 h3

In [8]:
h3 = rnn(x3, h2)
print(f'h3 = {h3}')

h3 = [0.98558989 0.98519418 0.99712029 0.99896154]


# 3.續上一題，假設 x1、x2、x3 為 Encoder (冒險 26) 時期所輸入的三個字，假設目前在 Decoder 時期 t=3 的時間點，且 S3 = [2, 5, 3, 1] (Querry 向量)

## 計算注意力強度

In [9]:
import numpy as np

S3 = np.array([2, 5, 3, 1])

e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)

e = np.array([e1, e2, e3])
print(f'e = {e}')

e = [ 7.41041537 10.72986601 10.8874731 ]


## 定義 softmax 函數

In [10]:
def softmax(x):
  c=np.max(x)
  x = x - c
  return np.exp(x) / np.sum(np.exp(x))

## 注意力大小轉換

In [11]:
alpha = softmax(e)
print(f'alpha = {alpha}')

alpha = [0.01639089 0.45312864 0.53048047]


## 計算 c3

In [12]:
c3 = alpha[0]*h1 + alpha[1]*h2 + alpha[2]*h3
print(f'c3 = {c3}')

c3 = [0.96439732 0.97607545 0.98580058 0.9924911 ]


# 4.請完成課本冒險旅程 28 第 1, 2, 3 題

## 建立輸入的向量及對應的矩陣

In [13]:
import numpy as np

# x1, x2, x3合併為一個輸入 X
X = np.array([x1, x2, x3])
print(f'X =\n {X}')

# 定義 WQ, WK, WV 權重矩陣
WQ = np.array([[0, 0, 1],
        [1, 0, 0],
        [0, 0, 1]])

WK = np.array([[1, 0, 1],
        [0, 1, 1],
        [0, 1, 0]])

WV = np.array([[0, 2, 1],
        [1, 0, 3],
        [1, 0, 1]])

X =
 [[0.1 0.2 0.3]
 [0.4 0.1 0.5]
 [0.6 0.2 0.1]]


## 計算 Q, K, V

In [14]:
Q = np.dot(X, WQ)
K = np.dot(X, WK)
V = np.dot(X, WV)

print(f'Q =\n {Q}')
print(f'K =\n {K}')
print(f'V =\n {V}')

Q =
 [[0.2 0.  0.4]
 [0.1 0.  0.9]
 [0.2 0.  0.7]]
K =
 [[0.1 0.5 0.3]
 [0.4 0.6 0.5]
 [0.6 0.3 0.8]]
V =
 [[0.5 0.2 1. ]
 [0.6 0.8 1.2]
 [0.3 1.2 1.3]]


## Attention(Q,K,V)


In [33]:
d_k = K.shape[1]
K_T = np.transpose(K)
scores = np.dot(Q, K_T) / np.sqrt(d_k)

# 每一列做 softmax
weights = np.apply_along_axis(softmax, axis=1, arr=scores)

# self-attention
context = np.dot(weights, V)
print(f'self-attention =\n {context}')

self-attention =
 [[0.46046692 0.76200892 1.1752271 ]
 [0.45552503 0.78090496 1.18079022]
 [0.45697791 0.77621357 1.17942958]]


## 驗證：計算 q1, k1, v1

In [34]:
q1 = np.dot(X[0], WQ)
k1 = np.dot(X[0], WK)
v1 = np.dot(X[0], WV)

print(f'Q第一列: {Q[0]}')
print(f'q1: {q1}\n')

print(f'K第一列: {K[0]}')
print(f'k1: {k1}\n')

print(f'V第一列: {V[0]}')
print(f'v1: {v1}')

Q第一列: [0.2 0.  0.4]
q1: [0.2 0.  0.4]

K第一列: [0.1 0.5 0.3]
k1: [0.1 0.5 0.3]

V第一列: [0.5 0.2 1. ]
v1: [0.5 0.2 1. ]
